packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: false
patchedDependencies:
  '@react-native-oh/react-native-harmony-cli@0.84.1': patches/@react-native-oh__react-native-harmony-cli@0.84.1.patch
