import { useCallback } from "react";
import { useTranslation } from "react-i18next";
import { generateId } from "@neo-tavern/shared";
import { useWorldbookStore } from "@/features/settings/worldbook.store";
import { characterRepository, worldbookRepository } from "@/db/repositories";
import { toast } from "@/utils/toast";
import type { Character, CreateCharacterInput, UpdateCharacterInput, Worldbook } from "@neo-tavern/shared";
import type { BuilderTarget, WorldbookDraft } from "../types";
import { NEW_TARGET } from "../types";
import type { NeoStatusBarConfig } from "@/features/character/neo-character-builder";

interface UseBuilderSaveOptions {
  draft: CreateCharacterInput | null;
  worldbookDraft: WorldbookDraft | null;
  statusBars: NeoStatusBarConfig | null;
  savedCharacterId: string | null;
  targetId: BuilderTarget;
  setSaving: (saving: boolean) => void;
  setTargetId: (id: BuilderTarget) => void;
  setSavedCharacterId: (id: string | null) => void;
  loadCharacters: () => Promise<void>;
  createCharacter: (input: CreateCharacterInput) => Promise<Character>;
  updateCharacter: (id: string, input: UpdateCharacterInput) => Promise<Character>;
}

export function useBuilderSave(opts: UseBuilderSaveOptions) {
  const { t: tt } = useTranslation("toast");
  const {
    draft,
    worldbookDraft,
    statusBars,
    savedCharacterId,
    targetId,
    setSaving,
    setTargetId,
    setSavedCharacterId,
    loadCharacters,
    createCharacter,
    updateCharacter,
  } = opts;

  const handleSave = useCallback(async () => {
    if (!draft?.name.trim()) return;

    const findExistingCharacterIdForSave = async (nextDraft: CreateCharacterInput) => {
      const candidateIds = [savedCharacterId, targetId !== NEW_TARGET ? targetId : null, nextDraft.id]
        .filter((id): id is string => !!id)
        .filter((id, index, array) => array.indexOf(id) === index);

      for (const id of candidateIds) {
        if (await characterRepository.getById(id)) return id;
      }

      const normalizedName = nextDraft.name.trim();
      if (!normalizedName) return null;
      const sameName = (await characterRepository.list(true)).filter(
        (character) => character.name.trim() === normalizedName,
      );
      return sameName.length === 1 ? sameName[0].id : null;
    };

    const saveWorldbookForCharacter = async (character: Character, nextWorldbookDraft: WorldbookDraft) => {
      const now = new Date().toISOString();
      const worldbooks = useWorldbookStore.getState().worldbooks;
      const existingWorldbook = character.worldbookId
        ? worldbooks.find((worldbook) => worldbook.id === character.worldbookId)
        : null;
      const worldbookId = existingWorldbook?.id || generateId();
      const worldbook: Worldbook = {
        id: worldbookId,
        name: nextWorldbookDraft.name || `${character.name} Worldbook`,
        description: nextWorldbookDraft.description || `Generated by Whale Builder for ${character.name}`,
        entries: nextWorldbookDraft.entries.map((entry) => ({
          ...entry,
          id: generateId(),
          worldbookId,
          createdAt: now,
          updatedAt: now,
        })),
        createdAt: existingWorldbook?.createdAt || now,
        updatedAt: now,
      };

      const nextWorldbooks = existingWorldbook
        ? worldbooks.map((item) => (item.id === worldbookId ? worldbook : item))
        : [...worldbooks, worldbook];

      await worldbookRepository.save(nextWorldbooks);
      useWorldbookStore.getState().loadWorldbooks();
      useWorldbookStore.getState().setActiveWorldbook(worldbookId);
      return updateCharacter(character.id, { worldbookId });
    };

    setSaving(true);
    try {
      const nextDraft = { ...draft, statusBars: statusBars ?? draft.statusBars };
      const existingCharacterId = await findExistingCharacterIdForSave(nextDraft);
      let saved = existingCharacterId
        ? await updateCharacter(existingCharacterId, nextDraft)
        : await createCharacter(nextDraft);
      setTargetId(saved.id);

      if (worldbookDraft?.entries.length) {
        saved = await saveWorldbookForCharacter(saved, worldbookDraft);
        setTargetId(saved.id);
      }

      setSavedCharacterId(saved.id);
      await loadCharacters();
      toast("success", tt("saveSuccess", { name: saved.name }));
    } catch (err) {
      const message = (err as Error).message || tt("saveFailed");
      toast("error", message);
    } finally {
      setSaving(false);
    }
  }, [
    draft,
    worldbookDraft,
    statusBars,
    savedCharacterId,
    targetId,
    setSaving,
    setTargetId,
    setSavedCharacterId,
    loadCharacters,
    createCharacter,
    updateCharacter,
    tt,
  ]);

  return { handleSave };
}
